import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@admin.com',
      password: bcrypt.hashSync('admin'),
      isAdmin: true,
    },
    {
      name: 'Pedro',
      email: 'pedro@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Violão Clássico Yamaha',
      slug: 'violao-classico-yamaha',
      category: 'Violões',
      image: '/images/violao1.jpg',
      price: 450,
      brand: 'Yamaha',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Violão clássico de alta qualidade com som cristalino',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Guitarra Elétrica Fender',
      slug: 'guitarra-eletrica-fender',
      category: 'Guitarras',
      image: '/images/guitarra1.jpg',
      price: 1200,
      brand: 'Fender',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Guitarra elétrica profissional com som potente',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Teclado Casio 61 Teclas',
      slug: 'teclado-casio-61',
      category: 'Teclados',
      image: '/images/teclado1.png',
      price: 350,
      brand: 'Casio',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Teclado compacto com 61 teclas e múltiplos sons',
    },
    {
      name: 'Bateria Acústica Pearl',
      slug: 'bateria-acustica-pearl',
      category: 'Baterias',
      image: '/images/bateria1.jpg',
      price: 2500,
      brand: 'Pearl',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Bateria acústica profissional com som excelente',
    },
    {
      name: 'Saxofone Alto Yamaha',
      slug: 'saxofone-alto-yamaha',
      category: 'Sopros',
      image: '/images/saxofone1.jpg',
      price: 1800,
      brand: 'Yamaha',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Saxofone alto com som quente e responsivo',
    },
    {
      name: 'Baixo Elétrico Ibanez',
      slug: 'baixo-eletrico-ibanez',
      category: 'Baixos',
      image: '/images/baixo1.jpg',
      price: 900,
      brand: 'Ibanez',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Baixo elétrico com som profundo e dinâmico',
    },
    {
      name: 'Fender Squier Jazz Bass',
      slug: 'baixo-eletrico-squier',
      category: 'Baixos',
      image: '/images/baixo2.jpg',
      price: 3500,
      brand: 'Squier',
      rating: 4.1,
      numReviews: 51,
      countInStock: 5,
      description: 'Baixo 5 Cordas Fender Squier Affinity Series® Active Jazz Bass® V Black Metallic',
    },    
    {
      name: 'Yamaha TRBX305',
      slug: 'baixo-eletrico-yamaha',
      category: 'Baixos',
      image: '/images/baixo3.jpg',
      price: 4500,
      brand: 'yamaha',
      rating: 4.0,
      numReviews: 49,
      countInStock: 8,
      description: 'A perfeita combinação entre design moderno, engenharia precisa e a construção milenar da Yamaha.',
    }, 
    {
      name: 'Marcus Miller Sire V7',
      slug: 'baixo-eletrico-sire',
      category: 'Baixos',
      image: '/images/baixo4.jpg',
      price: 8000,
      brand: 'sire',
      rating: 3.8,
      numReviews: 6,
      countInStock: 20,
      description: 'Sendo o principal modelo de baixo Sire, o V7 é inovador para produzir o som característico de Marcus Miller.',
    },
    {
    name: 'Yamaha PSR-E373',
    slug: 'teclado-yamaha-psr-e373',
    category: 'Teclados',
    image: '/images/teclado4.jpg',
    price: 2500,
    brand: 'Yamaha',
    rating: 4.5,
    numReviews: 18,
    countInStock: 15,
    description: 'O Yamaha PSR-E373 oferece uma ampla variedade de sons e recursos, ideal para iniciantes e músicos intermediários.',
  },
  {
    name: 'Yamaha MX61 V2',
    slug: 'teclado-yamaha-mx61-v2',
    category: 'Teclados',
    image: '/images/teclado2.jpg',
    price: 6200,
    brand: 'Yamaha',
    rating: 4.7,
    numReviews: 24,
    countInStock: 10,
    description: 'O MX61 combina sons autênticos dos sintetizadores Motif com controle total via USB, perfeito para produção e performance.',
  },
  {
    name: 'Yamaha P-125B',
    slug: 'piano-digital-yamaha-p125b',
    category: 'Teclados',
    image: '/images/teclado3.jpg',
    price: 5800,
    brand: 'Yamaha',
    rating: 4.9,
    numReviews: 31,
    countInStock: 8,
    description: 'O P-125B é um piano digital portátil com toque de piano acústico e som realista, ideal para estudos e apresentações.',
  },
     
  ],
}
export default data
